### PR TITLE
fix: disable ANSI colors when output is redirected

### LINKED ISSUE #600: cargo-wdk emits ANSI escape sequences when redirected to file
When cargo-wdk's output is redirected to a file it still writes ANSI escape sequences as shown below:

```
[32m INFO[0m Building package my-driver
[32m INFO[0m Copying files to target package folder: C:\Users\abc\code\my-driver\target\debug\my_driver_package
[32m INFO[0m Running stampinf
[32m INFO[0m Running inf2cat
...
```

Escape sequences are meant only for the console. It should skip them when redirected and the output should look like this:

```
INFO Building package my-driver
INFO Copying files to target package folder: C:\Users\abc\code\my-driver\target\debug\my_driver_package
INFO Running stampinf
INFO Running inf2cat
...
```

### PR DESCRIPTION
**Pull request by rockygeekz**
### Summary
This PR disables ANSI color output when `cargo-wdk` stderr is not a TTY.

When output is redirected to a file, ANSI escape sequences may currently be
emitted, resulting in unreadable logs. This change detects non-TTY output
and disables colorized logging, producing clean and readable text output
when redirected.

### Details
- Detects whether stderr is a terminal using `std::io::IsTerminal`
- Preserves colored output for interactive terminals
- Disables ANSI formatting when output is redirected to files or pipes
- No behavioral changes to logging levels or CLI functionality

### Rationale
ANSI escape sequences are intended for interactive terminals only.
Disabling them for non-TTY output aligns `cargo-wdk` with standard CLI
behavior (e.g. `cargo`, `git`, `ripgrep`).

### Notes
- This change only affects log presentation
- No tests were added as this behavior is environment-dependent and
  `init_tracing` currently has no test coverage

Fixes #600

### CODE REVIEW

File: crates/cargo-wdk/src/trace.rs [hunk 1]
```diff
@@ -28,13 +29,17 @@ pub fn init_tracing(verbosity_level: clap_verbosity_flag::Verbosity) {
 
     let tracing_filter = EnvFilter::default().add_directive(level.into());
 
+    let is_tty = std::io::stdout().is_terminal();
+
```
Comment (gurry) [inline crates/cargo-wdk/src/trace.rs]: Nit: just inline this instead of introducing a variable

File: crates/cargo-wdk/src/trace.rs [hunk 2]
```diff
@@ -28,13 +29,17 @@ pub fn init_tracing(verbosity_level: clap_verbosity_flag::Verbosity) {
...
     tracing_subscriber::fmt()
         .compact()
         .without_time()
         .with_target(false)
         .with_file(false)
         .with_env_filter(tracing_filter)
+        .with_ansi(is_tty)
         .init();
+
```
Comment (gurry) [inline crates/cargo-wdk/src/trace.rs]:
```suggestion
```
Remove this blank line

File: crates/cargo-wdk/src/trace.rs [hunk 3]
```diff
@@ -28,13 +29,17 @@ pub fn init_tracing(verbosity_level: clap_verbosity_flag::Verbosity) {
 
     let tracing_filter = EnvFilter::default().add_directive(level.into());
 
+    let is_tty = std::io::stdout().is_terminal();
```
Comment (gurry) [inline crates/cargo-wdk/src/trace.rs]: Do this for `stderr` instead of `stdout` as we have [another PR which moves the output to `stderr`](https://github.com/microsoft/windows-drivers-rs/pull/599) and we will merge that one first

**Comment by rockygeekz** [comment]
Updated, thanks!
