### PR TITLE
fix: improve error reporting when no wdk-build package is found

### LINKED ISSUE #334: `ConfigError::MultipleWdkBuildCratesDetected` can be thrown when 0 build crates are detected
In `crates/wdk-build/src/cargo_make.rs`, we throw an `ConfigError::MultipleWdkBuildCratesDetected` if wdk_build_package_matches.len() != 1. This is misleading if `wdk_build_package_matches.len() == 0`.

### PR DESCRIPTION
**Pull request by kehan-zhou**
**🛠️ What This Fix Does**
Previously, the code would throw `ConfigError::MultipleWdkBuildCratesDetected` even when no wdk-build packages were found. This was misleading since the error implied that multiple crates were detected.

This fix adds a more apparent distinction:
If no wdk-build crates are detected, a new `NoWdkBuildCrateDetected` error is returned.
If more than one is found, the existing `MultipleWdkBuildCratesDetected` is used.
This provides more accurate error reporting to users.

**📌 Related Issue**
Fixes #334

**🧪 Testing**
Ran `cargo test` locally to confirm no regressions and that the new error path is covered.

### CODE REVIEW

**Comment by kehan-zhou** [comment]
@microsoft-github-policy-service agree

File: crates/wdk-build/src/lib.rs [hunk 1]
```diff
@@ -187,6 +187,10 @@ pub enum ConfigError {
     #[error(transparent)]
     CargoMetadataError(#[from] cargo_metadata::Error),
 
+    /// Error returned when no wdk-build crate is detected
+    #[error("no wdk-build crate was detected in this workspace")]
```
Comment (gurry) [inline crates/wdk-build/src/lib.rs]:
```suggestion
    #[error("no wdk-build package was detected in this workspace")]
```
Makes this error message consistent with the error message on the `MultipleWdkBuildCratesDetected` error

Comment (kehan-zhou) [reply crates/wdk-build/src/lib.rs]: Thanks for the suggestion. I've updated the error message to match the style of the `MultipleWdkBuildCratesDetected` error.

**Review by gurry — APPROVED** [review]

**Comment by kehan-zhou** [comment]
I just rebased the branch on top of the latest `main` and I've applied the suggested changes. Let me know if there's anything else you'd like me to adjust.

**Review by gurry — APPROVED** [review]
